packages:
  - 'client'
  - 'server'

catalog:
  typescript: '5.8.2'
  graphql: '16.10.0'
  eslint: '9.21.0'
  '@types/node': '22.13.8'
  prettier: '3.5.2'
  '@typescript-eslint/eslint-plugin': '8.25.0'
  '@typescript-eslint/parser': '8.25.0'
  'eslint-config-prettier': '10.0.2'
  'eslint-plugin-prettier': '5.2.3'
