name: Node Client Test CI

on:
  push:
    paths:
      - "client/**"
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build, and test
        working-directory: client
        run: |
          yarn set version stable
          yarn install --immutable
          yarn build
          yarn test
        env:
          CI: true
